server:
  port: 8092
spring:
  application:
    name: appraise-service
  data:
    # MongoDB 配置项，对应 MongoProperties 类
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: leyou
      username: leyou
      password: leyou
      # 上述属性，也可以只配置 uri

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

ly:
  jwt:
    pubKeyPath: E:\ziyou-ssh-key\ziyou-key.pub # 公钥地址
    cookie:
      cookieName: ZY_TOKEN # cookie名称
    app:
      id: 11
      serviceName: appraise-service

logging:
  level:
    com.leyou: debug # 打印 mongodb 操作的具体语句。生产环境下，不建议开启。